/* Voice Synth Archive Playlist Lab v24 */
(function(){
"use strict";
const PK="vsa.playlists.v24", SK="vsa.smart.v23", OK="vsa.organizer.v22";
let store=load(PK,{version:1,playlists:[]});
let draft=[];
let dragIndex=-1;

function load(k,f){try{return Object.assign(f,JSON.parse(localStorage.getItem(k)||"null")||{})}catch(e){return f}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function fmt(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString("ko-KR"):"-"}
function clamp(v){return Math.max(0,Math.min(1,v))}
function uniq(a){return [...new Set((a||[]).filter(Boolean))]}
function uid(){return "pl_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,8)}
function toast24(m){try{toast(m)}catch(e){console.log(m)}}
function tags(s){const r=s&&s.tags;if(Array.isArray(r))return r.map(String).filter(Boolean);return String(r||"").split(/[,\s　、]+/).map(x=>x.trim()).filter(Boolean)}
function generic(t){return /^VOCALOID$/i.test(t)||/オリジナル曲|伝説入り|殿堂入り|神話入り|ミリオン/.test(t)||/^(初音ミク|鏡音リン|鏡音レン|巡音ルカ|GUMI|IA|flower|KAITO|MEIKO)$/.test(t)}
function norm(s){if(!s)return null;return {contentId:String(s.contentId||""),title:String(s.title||s.contentId||""),viewCounter:+s.viewCounter||0,startTime:String(s.startTime||""),thumbnailUrl:String(s.thumbnailUrl||""),tags:Array.isArray(s.tags)?s.tags.slice(0,100):String(s.tags||"")}}
function sim(a,b){const A=new Set(tags(a).filter(t=>!generic(t))),B=new Set(tags(b).filter(t=>!generic(t)));if(!A.size||!B.size)return 0;let n=0;A.forEach(t=>{if(B.has(t))n++});return n/Math.max(1,new Set([...A,...B]).size)}
function hidden(s){return 1-clamp(Math.log1p(Math.max(0,+s.viewCounter||0))/Math.log1p(10000000))}
function smart(){const x=load(SK,{feedback:{},tagPrefs:{},lastMix:[]});x.feedback=x.feedback||{};x.tagPrefs=x.tagPrefs||{};return x}
function org(){return load(OK,{library:{}})}
function refs(){const s=smart(),o=org(),a=[];Object.values(o.library||{}).forEach(x=>{if((x.status==="favorite"||x.status==="interest")&&x.song)a.push(norm(x.song))});Object.values(s.feedback||{}).forEach(x=>{if(+x.value>0&&x.song)a.push(norm(x.song))});return a.slice(0,40)}
function prefMap(){const s=smart(),m=new Map();Object.entries(s.tagPrefs||{}).forEach(([t,v])=>m.set(t,(+v||0)*4));const o=org();Object.values(o.library||{}).forEach(x=>{const w=x.status==="favorite"?3:x.status==="interest"?2:x.status==="investigate"?1:0;if(!w||!x.song)return;tags(x.song).filter(t=>!generic(t)).forEach(t=>m.set(t,(m.get(t)||0)+w))});Object.values(s.feedback||{}).forEach(x=>{const w=(+x.value||0)*3;if(!w||!x.song)return;tags(x.song).filter(t=>!generic(t)).forEach(t=>m.set(t,(m.get(t)||0)+w))});return m}
function metrics(song){const pm=prefMap(),st=new Set(tags(song)),r=refs();let pos=0,neg=0,ms=0;pm.forEach((w,t)=>{if(st.has(t)){if(w>0)pos+=Math.min(8,w);else neg+=Math.min(8,-w)}});r.forEach(x=>{ms=Math.max(ms,sim(song,x))});return {strength:clamp(pos/18-neg/22),novelty:1-ms,hidden:hidden(song)}}
function row(song){return {song:norm(song),metrics:metrics(song)}}
function currentCfg(){return {novelty:+((document.getElementById("v24Novelty")||{}).value)||55,depth:+((document.getElementById("v24Depth")||{}).value)||55,excludeHeard:!!(document.getElementById("v24ExcludeHeard")||{}).checked}}
function score(r,cfg){return r.metrics.strength*.55+r.metrics.novelty*(cfg.novelty/100)*.25+r.metrics.hidden*(cfg.depth/100)*.30}
function reason(r){const pm=prefMap(),st=new Set(tags(r.song)),good=[...pm.entries()].filter(x=>x[1]>0&&st.has(x[0])).sort((a,b)=>b[1]-a[1]).slice(0,4).map(x=>x[0]),bad=[...pm.entries()].filter(x=>x[1]<0&&st.has(x[0])).slice(0,2).map(x=>x[0]),a=[];if(good.length)a.push("취향 "+good.join(", "));a.push("추천 "+Math.round(r.metrics.strength*100));a.push("새로움 "+Math.round(r.metrics.novelty*100));a.push("숨음 "+Math.round(r.metrics.hidden*100));if(bad.length)a.push("감점 "+bad.join(", "));return a.join(" · ")}
function pool(){const map=new Map();try{[state.songs,state.tasteSongs,state.guideSongs,state.hiddenGems,state.hiddenGemPool,state.detectiveCandidates].forEach(g=>{if(!Array.isArray(g))return;g.forEach(x=>{const s=(x&&x.song)||x;if(s&&s.contentId)map.set(s.contentId,norm(s))})})}catch(e){};const sm=smart();(sm.lastMix||[]).forEach(s=>{if(s&&s.contentId)map.set(s.contentId,norm(s))});return [...map.values()]}
function importLast(){const a=(smart().lastMix||[]).map(norm).filter(Boolean);if(!a.length){toast24("먼저 스마트 믹스를 한 번 만들어주세요.");return}draft=a.map(row);applyFilters();render();renderPrefs();toast24("최근 스마트 믹스를 가져왔습니다.")}
function applyFilters(){const cfg=currentCfg(),o=org();if(cfg.excludeHeard)draft=draft.filter(r=>!(o.library&&o.library[r.song.contentId]&&o.library[r.song.contentId].status==="heard"));draft=draft.map(r=>row(r.song)).sort((a,b)=>score(b,cfg)-score(a,cfg));render()}
function replaceOne(i){if(!draft[i])return;const used=new Set(draft.map(x=>x.song.contentId)),target=draft[i].song,cfg=currentCfg();const cand=pool().filter(s=>!used.has(s.contentId)).map(s=>{const r=row(s);return {r,v:score(r,cfg)+sim(target,s)*.35}}).sort((a,b)=>b.v-a.v);if(!cand.length){toast24("교체 후보가 부족합니다. 검색/추천을 더 실행해 후보 풀을 늘려주세요.");return}draft[i]=cand[0].r;render();renderPrefs();toast24("한 곡을 교체했습니다.")}
function move(i,d){const j=i+d;if(i<0||j<0||i>=draft.length||j>=draft.length)return;[draft[i],draft[j]]=[draft[j],draft[i]];render()}
function render(){const box=document.getElementById("v24Draft");if(!box)return;if(!draft.length){box.innerHTML='<div class="v24-empty">최근 스마트 믹스를 가져오거나 저장 목록을 불러오세요.</div>';return}box.innerHTML=draft.map((r,i)=>{const s=r.song,y=s.startTime?new Date(s.startTime).getFullYear():"-";return '<article class="v24-row" draggable="true" data-i="'+i+'"><div class="v24-drag">⋮⋮</div><div class="v24-num">'+(i+1)+'</div>'+(s.thumbnailUrl?'<img src="'+esc(s.thumbnailUrl)+'" loading="lazy">':'<div class="v24-noimg"></div>')+'<div class="v24-main"><a href="https://www.nicovideo.jp/watch/'+encodeURIComponent(s.contentId)+'" target="_blank" rel="noopener">'+esc(s.title||s.contentId)+'</a><small>'+y+' · 조회 '+fmt(s.viewCounter)+'</small><div class="v24-metrics"><span>추천 '+Math.round(r.metrics.strength*100)+'</span><span>새로움 '+Math.round(r.metrics.novelty*100)+'</span><span>숨음 '+Math.round(r.metrics.hidden*100)+'</span></div><details><summary>왜 추천?</summary><div class="v24-why">'+esc(reason(r))+'</div></details><div class="v24-actions"><button class="mini-btn" data-up="'+i+'">↑</button><button class="mini-btn" data-down="'+i+'">↓</button><button class="mini-btn" data-replace="'+i+'">한 곡 교체</button><button class="mini-btn" data-remove="'+i+'">제거</button></div></div></article>'}).join("");bindDrag()}
function bindDrag(){document.querySelectorAll(".v24-row").forEach(el=>{el.addEventListener("dragstart",e=>{dragIndex=+el.dataset.i;e.dataTransfer.effectAllowed="move"});el.addEventListener("dragover",e=>e.preventDefault());el.addEventListener("drop",e=>{e.preventDefault();const to=+el.dataset.i;if(dragIndex<0||to===dragIndex)return;const x=draft.splice(dragIndex,1)[0];draft.splice(to,0,x);dragIndex=-1;render()});el.addEventListener("dragend",()=>dragIndex=-1)})}
function saveList(){if(!draft.length){toast24("저장할 목록이 없습니다.");return}const n=(document.getElementById("v24Name")||{}).value||("스마트 믹스 "+new Date().toLocaleDateString("ko-KR"));store.playlists.unshift({id:uid(),name:String(n).trim().slice(0,60),createdAt:Date.now(),updatedAt:Date.now(),songs:draft.map(x=>x.song)});store.playlists=store.playlists.slice(0,60);save(PK,store);renderSaved();toast24("저장했습니다.")}
function loadList(id){const x=store.playlists.find(p=>p.id===id);if(!x)return;draft=(x.songs||[]).map(row);const n=document.getElementById("v24Name");if(n)n.value=x.name;render();renderPrefs()}
function dup(id){const x=store.playlists.find(p=>p.id===id);if(!x)return;store.playlists.unshift({...x,id:uid(),name:x.name+" 복사본",createdAt:Date.now(),updatedAt:Date.now(),songs:(x.songs||[]).map(s=>({...s}))});save(PK,store);renderSaved()}
function rename(id){const x=store.playlists.find(p=>p.id===id);if(!x)return;const n=prompt("플레이리스트 이름",x.name);if(!n||!n.trim())return;x.name=n.trim().slice(0,60);x.updatedAt=Date.now();save(PK,store);renderSaved()}
function removeSaved(id){if(!confirm("이 플레이리스트를 삭제할까요?"))return;store.playlists=store.playlists.filter(x=>x.id!==id);save(PK,store);renderSaved()}
function renderSaved(){const box=document.getElementById("v24Saved");if(!box)return;if(!store.playlists.length){box.innerHTML='<div class="v24-empty small">저장된 플레이리스트가 없습니다.</div>';return}box.innerHTML=store.playlists.map(x=>'<div class="v24-saved"><div><b>'+esc(x.name)+'</b><small>'+((x.songs||[]).length)+'곡</small></div><div><button class="mini-btn" data-load="'+x.id+'">불러오기</button><button class="mini-btn" data-dup="'+x.id+'">복제</button><button class="mini-btn" data-rename="'+x.id+'">이름</button><button class="mini-btn danger" data-del="'+x.id+'">삭제</button></div></div>').join("")}
function copyList(){if(!draft.length)return;const t=draft.map((x,i)=>(i+1)+". "+x.song.title+" https://www.nicovideo.jp/watch/"+x.song.contentId).join("\n");if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(t).then(()=>toast24("링크 목록을 복사했습니다."));else{const a=document.createElement("textarea");a.value=t;document.body.appendChild(a);a.select();document.execCommand("copy");a.remove();toast24("링크 목록을 복사했습니다.")}}
function prefCandidates(){const sm=smart(),pm=prefMap(),cnt=new Map();draft.forEach(r=>tags(r.song).filter(t=>!generic(t)).forEach(t=>cnt.set(t,(cnt.get(t)||0)+1)));return uniq([...Object.keys(sm.tagPrefs||{}),...[...pm.entries()].filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,14).map(x=>x[0]),...[...cnt.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>x[0])]).slice(0,28)}
function renderPrefs(){const box=document.getElementById("v24Prefs");if(!box)return;const sm=smart(),a=prefCandidates();if(!a.length){box.innerHTML='<div class="v24-empty small">취향 데이터가 쌓이면 태그가 나타납니다.</div>';return}box.innerHTML=a.map(t=>{const v=+sm.tagPrefs[t]||0;return '<button class="v24-pref '+(v>0?'plus':v<0?'minus':'')+'" data-tag="'+esc(t)+'"><span>'+esc(t)+'</span><b>'+(v>0?'+':v<0?'−':'·')+'</b></button>'}).join("")}
function cycleTag(t){const sm=smart(),v=+sm.tagPrefs[t]||0;if(v===0)sm.tagPrefs[t]=1;else if(v>0)sm.tagPrefs[t]=-1;else delete sm.tagPrefs[t];save(SK,sm);renderPrefs();draft=draft.map(r=>row(r.song));render()}
function addTag(){const e=document.getElementById("v24Tag"),t=e&&e.value.trim();if(!t)return;const sm=smart();sm.tagPrefs[t]=1;save(SK,sm);e.value="";renderPrefs();draft=draft.map(r=>row(r.song));render()}
function labels(){const n=document.getElementById("v24NoveltyVal"),d=document.getElementById("v24DepthVal");if(n)n.textContent=(document.getElementById("v24Novelty")||{}).value||55;if(d)d.textContent=(document.getElementById("v24Depth")||{}).value||55}
function style(){const s=document.createElement("style");s.textContent=[
".v24-panel{min-height:620px}.v24-layout{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr);gap:10px;padding:10px}",
".v24-box{border:1px solid #203a55;border-radius:15px;background:#091624;overflow:hidden}.v24-head{padding:11px 12px;border-bottom:1px solid #203a55}.v24-head b{font-size:12px}.v24-head small{display:block;color:#7793aa;font-size:9px;margin-top:3px}",
".v24-toolbar,.v24-options,.v24-savebar,.v24-tagadd{display:flex;gap:6px;align-items:center;flex-wrap:wrap;padding:10px}.v24-toolbar input,.v24-savebar input,.v24-tagadd input{flex:1;min-width:140px}.v24-sliders{display:grid;grid-template-columns:1fr 1fr;gap:9px;padding:0 10px 10px}.v24-slider{border:1px solid #1f3a52;border-radius:11px;padding:8px;background:#081523}.v24-slider label{display:flex;justify-content:space-between;font-size:9px;color:#a5bfd4}.v24-slider input{width:100%;margin-top:6px}",
".v24-row{display:grid;grid-template-columns:22px 28px 84px 1fr;gap:7px;align-items:center;padding:7px 8px;border-bottom:1px solid #132a40}.v24-drag{cursor:grab;color:#64849f}.v24-num{font-size:10px;font-weight:900;color:#7fa8c6;text-align:center}.v24-row img,.v24-noimg{width:84px;aspect-ratio:16/9;object-fit:cover;border-radius:8px;background:#122337}.v24-main{min-width:0}.v24-main>a{display:block;color:#e9f7ff;text-decoration:none;font-size:10px;font-weight:850;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v24-main>small{display:block;color:#7793aa;font-size:8px;margin-top:3px}.v24-metrics,.v24-actions{display:flex;gap:4px;flex-wrap:wrap;margin-top:5px}.v24-metrics span{font-size:8px;border:1px solid #29465e;border-radius:999px;padding:3px 5px;color:#a7c5d9}.v24-main summary{cursor:pointer;font-size:8px;color:#85bada}.v24-why{font-size:8px;color:#819cb3;line-height:1.55;padding-top:4px}",
".v24-saved{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:9px;border-bottom:1px solid #142b41}.v24-saved b{display:block;font-size:10px}.v24-saved small{display:block;font-size:8px;color:#7895ad;margin-top:3px}.v24-saved>div:last-child{display:flex;gap:4px;flex-wrap:wrap}.v24-prefwrap{display:flex;gap:5px;flex-wrap:wrap;padding:10px}.v24-pref{border:1px solid #29465e;background:#0b1c2c;color:#aec6d9;border-radius:999px;padding:5px 7px;font-size:9px}.v24-pref.plus{border-color:#3f8d78;background:#0d2d28;color:#c7f8e9}.v24-pref.minus{border-color:#7b3f50;background:#2a141b;color:#ffc2ce}.v24-empty{padding:42px 15px;text-align:center;color:#7793aa;font-size:10px;line-height:1.6}.v24-empty.small{padding:22px 12px}",
"@media(max-width:760px){.v24-layout{grid-template-columns:1fr}.v24-sliders{grid-template-columns:1fr}.v24-row{grid-template-columns:18px 22px 68px 1fr}.v24-row img,.v24-noimg{width:68px}.v24-saved{align-items:flex-start;flex-direction:column}}"
].join("");document.head.appendChild(s)}
function ui(){style();const tabs=document.getElementById("toolsTabs"),body=document.querySelector("#toolsModal .tools-body");if(!tabs||!body||document.querySelector('[data-tool="playlist24"]'))return;const tab=document.createElement("button");tab.dataset.tool="playlist24";tab.textContent="플레이리스트";tabs.appendChild(tab);const sec=document.createElement("section");sec.className="panel tool-view v24-panel";sec.dataset.toolView="playlist24";sec.innerHTML='<div class="panel-head"><div><h2>플레이리스트 연구실</h2><p>스마트 믹스를 가져와 저장·정렬·교체하고 취향을 세밀하게 조절합니다.</p></div><div class="pill">v24</div></div><div class="v24-layout"><div class="v24-box"><div class="v24-head"><b>현재 플레이리스트</b><small>드래그 또는 ↑↓로 순서 변경</small></div><div class="v24-toolbar"><button class="btn primary" id="v24Import">최근 스마트 믹스 가져오기</button><button class="mini-btn" id="v24Reorder">설정으로 재정렬</button></div><div class="v24-sliders"><div class="v24-slider"><label><span>익숙함 ↔ 새로움</span><b id="v24NoveltyVal">55</b></label><input id="v24Novelty" type="range" min="0" max="100" value="55"></div><div class="v24-slider"><label><span>안전 추천 ↔ 심해 발굴</span><b id="v24DepthVal">55</b></label><input id="v24Depth" type="range" min="0" max="100" value="55"></div></div><div class="v24-options"><label class="check"><input id="v24ExcludeHeard" type="checkbox" checked> 들어본 곡 제외</label></div><div id="v24Draft"><div class="v24-empty">최근 스마트 믹스를 가져오거나 저장 목록을 불러오세요.</div></div><div class="v24-savebar"><input id="v24Name" placeholder="플레이리스트 이름"><button class="mini-btn" id="v24Save">저장</button><button class="mini-btn" id="v24Copy">링크 복사</button></div></div><div><div class="v24-box"><div class="v24-head"><b>태그 취향 조절</b><small>중립 → 선호(+) → 제외(−) → 중립</small></div><div class="v24-prefwrap" id="v24Prefs"></div><div class="v24-tagadd"><input id="v24Tag" placeholder="직접 태그 추가"><button class="mini-btn" id="v24TagAdd">+ 선호</button></div></div><div class="v24-box" style="margin-top:10px"><div class="v24-head"><b>저장한 플레이리스트</b><small>불러오기 · 복제 · 이름 변경 · 삭제</small></div><div id="v24Saved"></div></div></div></div>';body.appendChild(sec);bind();renderSaved();renderPrefs();labels()}
function bind(){document.addEventListener("click",e=>{const b=e.target.closest&&e.target.closest("button");if(!b)return;if(b.matches('#toolsTabs [data-tool="playlist24"]')){e.preventDefault();try{setToolView("playlist24")}catch(x){}renderSaved();renderPrefs();return}if(b.dataset.up!=null){move(+b.dataset.up,-1);return}if(b.dataset.down!=null){move(+b.dataset.down,1);return}if(b.dataset.remove!=null){draft.splice(+b.dataset.remove,1);render();return}if(b.dataset.replace!=null){replaceOne(+b.dataset.replace);return}if(b.dataset.load){loadList(b.dataset.load);return}if(b.dataset.dup){dup(b.dataset.dup);return}if(b.dataset.rename){rename(b.dataset.rename);return}if(b.dataset.del){removeSaved(b.dataset.del);return}if(b.dataset.tag){cycleTag(b.dataset.tag);return}});document.getElementById("v24Import")?.addEventListener("click",importLast);document.getElementById("v24Reorder")?.addEventListener("click",applyFilters);document.getElementById("v24Save")?.addEventListener("click",saveList);document.getElementById("v24Copy")?.addEventListener("click",copyList);document.getElementById("v24TagAdd")?.addEventListener("click",addTag);document.getElementById("v24Novelty")?.addEventListener("input",labels);document.getElementById("v24Depth")?.addEventListener("input",labels)}
function boot(){ui()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
window.VSAPlaylist24={render,importLast};
})();